### ISSUE TITLE
getting started

### ISSUE THREAD

**Issue by KI0100010101001100** [SupaplexOSM/OSM-Cycling-Quality-Index#11]
Hello,
I'm trying to obtain the data for the Kiel Region running the overpass-query for it. As I'm downloading the data ("Export result as GeoJSON to 'data/way_import.geojson") I'm saving it to the same folder as the Python-script (cycling_quality_index.py). However when I run the script in the python console of my QGIS it doesn't recognise the path. 
As I'm new to working with scripts I'd appreciate help with the code. It appears that the path is not correct:

_exec(Path('/Users/myname/Desktop/Master_Thesis/cycling_quality_index.py').read_text())
15:05:12 Start processing:
15:05:12 Read data...
15:05:12 [!] Error: No valid input file at "/Users/myname/Desktop/Master_Thesis/data/way_import.geojson".
15:05:12 Finished processing._

I want to use the Index-code for my thesis and try to compare it with other methods in assessing bike infrastructure quality.

**Comment by SupaplexOSM** [comment]
Hey, nice to see that you want to use the data for your thesis!

The default file path is "**data/**way_import.geojson", so you need to create an extra "data" folder – or adjust the path variables in the top of the script.

Does that work for you?

**Comment by KI0100010101001100** [comment]
Thank you, it worked perfectly now to create it for a small area in Kiel:) 

Due to time error, the overpass is not working for a greater area in Kiel yet. As I want to assess the whole Kiel area probably within my thesis, is there a way to run the overpass over a larger fragment or will I have to assess the overpass for several areas and then put them together?
