### ISSUE TITLE
Split Data Missing in columns

### ISSUE THREAD

**Issue by eMerzh** [SupaplexOSM/OSM-Cycling-Quality-Index#12]
Hello 👋 

The project is really fun, and i'm starting to bring my bicycle comunity to OSM with the help of that 💃 

At the moment, because the data are not as good as berlin yet, the result is a bit all over the place, 
but we are fixing it with the help of the data_missing column.

We use the frontend map of neuss  (copy of what berlin have) and it displays a the "missing gap score" via color.
But I think it would be interesting to filter out by type of missing data;
like maxspeed, light, width, ... 

i have a small prototype of patch, i can submit, 
what do you think?

**Comment by tordans** [comment]
Yes, happy to add this to the filters. 

Did not look at the data, yet. I general I would want the filter setup to stay as simple as possible.

**Comment by SupaplexOSM** [comment]
@eMerzh Updated the script today: Splitted it in multiple parts (for paramters, definitions and script) and added your recommended missing tag attributes. I have adapted your variant slightly, e.g. used different field names and added further attributes. Thanks for the suggestion!
