### ISSUE TITLE
Skip Construction=*

### ISSUE THREAD

**Issue by eMerzh** [SupaplexOSM/OSM-Cycling-Quality-Index#14]
Hello :) 

Not sure if it should be in initial query or in the later processing, 
but maybe we should skip the path/road if construction=yes for example

**Comment by SupaplexOSM** [comment]
`construction=yes` seems to be a very atypical way of marking a road as "under construction". Wouldn't you use `highway=construction` + `construction=*` or `construction:` as a life cycle prefix?

But I wonder whether it might make sense to include roads under construction if they are not newly built but only temporarily closed. The map is not actually supposed to be a "live map" and could then show the "general" status at such locations (before and possibly also after the construction work). But for that you would have to differentiate between construction of new and existing roads and I don't know how to do that...

**Comment by SupaplexOSM** [comment]
P.S. [OSM wiki says](https://wiki.openstreetmap.org/wiki/Tag:construction%3Dyes), `construction=yes` is deprecated and you shouldn't use it.

So if there are roads/path with this tagging, you shoud fix them :)

**Comment by SupaplexOSM** [comment]
P.P.S. It sometimes happens that constructions are removed by changing the highway value from `highway=construction` to the actual `highway=*` value and forgetting to delete the `construction` sub value (especially when new users are editing constructions). If you don't process roads with any `construction` value, you would probably produce more mistakes...

**Comment by eMerzh** [comment]
hum, interesting i think we can close this then
