### ISSUE TITLE
bicycle=no herausfiltern

### ISSUE THREAD

**Issue by tordans** [SupaplexOSM/OSM-Cycling-Quality-Index#2]
Unter https://www.osm-verkehrswende.org/cqi/map/?map=16.5%2F13.4097%2F52.4821 sieht man noch Wege mit `bicycle=no`, zB https://www.openstreetmap.org/way/1228318632#map=19/52.48167/13.40802

**Comment by SupaplexOSM** [comment]
Wird bereits herausgefiltert. Das `bicycle=no` im genannten Beispiel wurde dort erst vor 6 Tagen ergänzt – ein aktueller Datensatz wird sie nicht mehr enthalten.
