### ISSUE TITLE
`lane_markings=no` als Malus

### ISSUE THREAD

**Issue by tordans** [SupaplexOSM/OSM-Cycling-Quality-Index#3]
* https://www.osm-verkehrswende.org/cqi/map/?map=17%2F13.421%2F52.4652
* https://www.openstreetmap.org/way/836498470#map=19/52.46501/13.42023
* Mapillary https://www.mapillary.com/app/?z=17&lat=52.4651428&lng=13.4205895&panos=true&dateFrom=2022-01-01&pKey=704407304088834&focus=photo&x=0.3356753346667788&y=0.5757517909690081&zoom=0

<img width="958" alt="image" src="https://github.com/SupaplexOSM/OSM-Cycling-Quality-Index/assets/111561/b0fdd694-8a40-48ab-bab7-c593e7c2766e">

Die Wege sind grün, also "gut", aber fühlen sich nicht "gut zu fahren" an.

Ich vermute, weil auf der straße viel (schwerlast) verkehr ist und die breite insg. dafür zu schmal.

Ich denke, dass die `lane_markings=no` als indikator genutzt werden können für diese situation.

**Comment by SupaplexOSM** [comment]
Ich würde behaupten, das ist in erster Linie ein Darstellungs-/Interpretations-Problem. Der Index-Wert ist 53, und damit ziemlich mittelmäßig.

Die aktuelle Farbskala nutzt ein recht breites Farbspektrum, also nicht nur rot/gelb/grün, sondern insbesondere für die besonders guten Wege auch blau, um diese hervorzuheben. Meiner Meinung nach funktioniert diese Hervorherung recht gut. Aber in der Tat ist ein Grün-Ton für "mittelmäßige" Werte irreführend.

Ich werde bei Gelegenheit versuchen, die Grüntöne ins Positivere zu verschieben, sodass die rot-orange-gelb-Töne gestreckt werden und das "Mittelfeld" aus gelb besteht und nicht aus grün.

**Comment by SupaplexOSM** [comment]
Farbwerte wurden inzwischen angepasst. Es gibt inzwischen auch zwei verschiedene Wegetypen für "Fahrbahn mit Markierungen" und "Fahrbahn ohne Markierungen", bei denen die Breitenprozessierung unterschiedlich stattfindet. Da kann man sicher auch nochmal genauer nachdenken, wie sich Fahrbahnmarkierung eigentlich auf die Qualität auswirkt...
