### ISSUE TITLE
Breite Radschutzstreifen bei schalen 2-spurigen Fahrbahnen

### ISSUE THREAD

**Issue by tordans** [SupaplexOSM/OSM-Cycling-Quality-Index#4]
* https://www.osm-verkehrswende.org/cqi/map/?map=17.3%2F13.42222%2F52.46575
* https://www.openstreetmap.org/way/28812708
* Mapillary https://www.mapillary.com/app/?z=17&lat=52.465643&lng=13.421383099972&panos=true&dateFrom=2022-01-01&pKey=698771594835483&focus=photo&x=0.8243585180026797&y=0.6704450463997669&zoom=0

Die Straße ist hier zweispurig aber hat nicht die nötige Breite für 2 Spuren. Das bedeutet, dass die Autos den Schutzstreifen überfahren oder zumindest sehr nah dran fahren. In diesem Setup sind die 1.5 m Breite RVA nicht "gut", wie die Farbe suggeriert.

Evtl. ist das auch mit #3 zu lösen.

<img width="560" alt="image" src="https://github.com/SupaplexOSM/OSM-Cycling-Quality-Index/assets/111561/43172364-47f9-4672-8cb1-19d898e05931">

**Comment by SupaplexOSM** [comment]
Siehe auch #3: Der Index des Radschutzstreifens ist 52, also alles andere als "gut". Könnte sich erübrigen, wenn die Farbskala angepasst wird.
